# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
# SPDX-License-Identifier: MIT

site_name: Industrial MLLM Benchmark
site_description: Industrial MLLM Benchmark
site_author: Dieter Bogdoll <dieter.bogdoll@siemens.com>, Markus Geipel <markus.geipel@siemens.com>

repo_url: https://github.com/siemens-research/industrial-mllm-benchmark.git
edit_uri: tree/main/docs

copyright: "Copyright &copy; 2024 Siemens AG"

nav:
  - 'Home': index.md
  - 'Benchmark configuration':
    - 'Overview': overview.md
    - 'Add new taskset': new_taskset.md
    - 'Add new task': new_task.md
    - 'Add new model definition': new_model.md
    - 'Add new grader definition': new_grader.md
  - 'Contributing': CONTRIBUTING.md

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: en
  features:
    - navigation.instant

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.snippets:
      base_path: ./docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist
