# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python

on:
  push:
    branches: [ "main", "setup-github-actions"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'

    - run: poetry install

    - name: Check pre-commit
      run: poetry run pre-commit run -a

    - name: Build Wheel
      run: |
        poetry build
        mv dist/ docs/dist/

    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true

    - name: Build pages
      run: |
        mkdir _site
        cp -r examples/ _site/examples/
        tree
        poetry run mkdocs build -s -d _site

    - name: Upload Pages Folder
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
