# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
# SPDX-License-Identifier: MIT

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check and Deploy GH pages

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'

      - name: Install project dependencies
        run: poetry install

      - name: Run checks
        run: |
          poetry run pre-commit run -a
          poetry build

      - name: Configure GH pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Build GH pages
        run: |
          cp -r examples/ docs/examples/
          cp CONTRIBUTING.md docs/
          cp LICENSE docs/

          poetry run mkdocs build -s -d _site

      - name: Upload GH pages
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy GH pages
        id: deployment
        uses: actions/deploy-pages@v4
