# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
# SPDX-License-Identifier: MIT

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python pull request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'

    - run: poetry install
    - run: poetry run pre-commit run -a
    - run: poetry build

    - name: Build pages
      run: |
        mv dist/ docs/dist/
        cp -r examples/ docs/examples/
        cp CONTRIBUTING.md docs/
        cp LICENSE docs/

        poetry run mkdocs build -s -d _site
