# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python main branch

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'

    - run: poetry install

    - run: poetry run pre-commit run -a

    - run: poetry build

    - uses: actions/configure-pages@v5
      with:
        enablement: true

    - name: Build pages
      run: |
        mv dist/ docs/dist/
        cp -r examples/ docs/examples/
        cp CONTRIBUTING.md docs/
        cp LICENSE docs/

        poetry run mkdocs build -s -d _site

    - uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
